### ISSUE TITLE
Translations for validation errors are missing

### ISSUE THREAD

**Issue by rob006** [askvortsov1/flarum-moderator-warnings#1]
There seems to be some inconsistency in translations for validation. Some keys are missing (for example `askvortsov-moderator-warnings.forum.validation.public_comment_required`).

https://github.com/askvortsov1/flarum-moderator-warnings/blob/4b02e8abe46b267ff7a551d2a0dcac0421bbe3e3/src/Api/Controller/CreateWarningController.php#L59

And some existing translations (like `askvortsov-moderator-warnings.forum.warning_modal.no_content_given`) are never used.

**Comment by askvortsov1** [comment]
Fixed in https://github.com/askvortsov1/flarum-moderator-warnings/commit/5b92397e4bbba42772248138f6f0be4e5bce8a16, thank you for the report!
