### ISSUE TITLE
Support pluralization i emails

### ISSUE THREAD

**Issue by rob006** [askvortsov1/flarum-moderator-warnings#14]
Right now pluralization is not supported in email subject and body, so you can get email like "rob006 warned you with 1 strikes in some topic".

**Comment by askvortsov1** [comment]
Should now be possible with ICU MessageFormat!

**Comment by askvortsov1** [comment]
Should now be possible with ICU MessageFormat!

**Comment by rob006** [comment]
While language pack may translate this correctly, default English translation still does not handle plurals.

https://github.com/askvortsov1/flarum-moderator-warnings/blob/c0777a4d26096732a0fd0e1c7d97c0d14b1ebc94/resources/locale/en.yml#L13

**Comment by askvortsov1** [comment]
:facepalm:. Fixed in https://github.com/askvortsov1/flarum-moderator-warnings/commit/cb9e8f77dd70b6e701585da24d7fa2e182194865
