### ISSUE TITLE
v0.4.0 Beta 15: User cannot see warning, no email no notification

### ISSUE THREAD

**Issue by PeopleInside** [askvortsov1/flarum-moderator-warnings#15]
https://discuss.flarum.org/d/23228-moderator-warnings-extension/60

**Comment by PeopleInside** [comment]
Sure, unistalled the extension but now reinstalled for you.
Still confirm user cannot see alert and be not notified.

![SharedScreenshot](https://user-images.githubusercontent.com/5006150/103707433-e7651f80-4fae-11eb-9fa3-759a329ca77e.jpg)

Admin are able to see the warning
![SharedScreenshot 2](https://user-images.githubusercontent.com/5006150/103707609-3d39c780-4faf-11eb-97e3-bfd287e43813.jpg)

User not and no notification. Last one was of 2020 very old
![SharedScreenshot 1](https://user-images.githubusercontent.com/5006150/103707657-5478b500-4faf-11eb-9221-fc9f81b4eed9.jpg)

**Comment by askvortsov1** [comment]
Sorry, but I'm still unable to replicate this, even for suspended users.

**Comment by PeopleInside** [comment]
I'm closing this, at the moment I'm no more using this. Thanks
