### ISSUE TITLE
TextFormatter is unable to render Mentions

### ISSUE THREAD

**Issue by the-turk** [askvortsov1/flarum-moderator-warnings#3]
Hey @askvortsov1,

I see you added the TextFormatter support with **0.1.9** but it won't work with the Mentions extension. When you add a new warning with some mentions in it, you'll end up with a notice as a result of GET request:

```php
Notice: Trying to get property 'mentionsUsers' of non-object in ...\flarum\mentions\src\Listener\FormatUserMentions.php on line 22
```

**Steps to reproduce:**
1. Click "New Warning" button.
2. Mention someone using `@whoever` in the comment section.
3. Refresh the page.
4. See the notice.

___

This was the exact reason why I did this trick here in the Diff extension:

https://github.com/the-turk/flarum-diff/blob/8b660cf2e51e19a940fa6cdf33136770b38aa723/src/Listeners/AddDiffRelationship.php#L305-L327

It fixes the issue but I'm not happy with it so I'll be glad if you can find a more clean solution for this.

**Comment by askvortsov1** [comment]
Hmm this is something I hadn't considered, thanks for bringing it up! Tbh, I'm not sure that mentions are needed in text formatter? I'll see if it can't be tweaked so that mentions don't evaluate.

**Comment by the-turk** [comment]
https://github.com/FriendsOfFlarum/moderator-notes/commit/27afa0c754ff9e6546cf6ce32ff24166334e013c

it's indeed more clear than mine 😄

**Comment by askvortsov1** [comment]
Thanks for finding this! I'll definitely _steal Ian's work_ fix this bug shortly!
