### ISSUE TITLE
Emails not translatable?

### ISSUE THREAD

**Issue by JCKodel** [askvortsov1/flarum-moderator-warnings#5]
E-mails are in english and linguist don't show any translations available.

**Comment by askvortsov1** [comment]
Due to https://github.com/flarum/core/issues/1934, email notifications are currently not translatable. Support for translating them was added in https://github.com/flarum/core/pull/2169, so when beta 14 is released, I'll update this extension to add this functionality.

**Comment by askvortsov1** [comment]
Emails should now be fully translatable
